services:
  # A Docker web service
  - type: web
    name: IOT
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r req.txt
    startCommand: uvicorn test:app --host 0.0.0.0 --port $PORT